DROP SEQUENCE MVCBOARDSEQ;
DROP TABLE MVCBOARD;

CREATE SEQUENCE MVCBOARDSEQ;

CREATE TABLE MVCBOARD(
	SEQ NUMBER PRIMARY KEY,
	WRITER VARCHAR2(100) NOT NULL,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	REGDATE DATE NOT NULL
);

INSERT INTO MVCBOARD
VALUES (MVCBOARDSEQ.NEXTVAL, '라이터', 'MVC 테스트', 'MVC는 계속 할거에요', SYSDATE);

SELECT SEQ, WRITER, TITLE, CONTENT, REGDATE
FROM MVCBOARD
ORDER BY SEQ DESC;


SELECT B.SEQ, B.WRITER, B.TITLE, B.CONTENT, B.REGDATE 
FROM 
	(SELECT ROWNUM AS RNUM, A.SEQ, A.WRITER, A.TITLE, A.CONTENT, A.REGDATE FROM 
	(SELECT SEQ, WRITER, TITLE, CONTENT, REGDATE FROM MVCBOARD
ORDER BY SEQ DESC) A
WHERE ROWNUM <= 23 ) B 
WHERE B.RNUM > 0;


INSERT INTO MVCBOARD
VALUES (MVCBOARDSEQ.NEXTVAL, '테스트', '페이징을 위한', '성공인가유?', SYSDATE);