DROP TABLE LOGIN;

CREATE TABLE LOGIN(
	USERID VARCHAR2(500) NOT NULL,
	PASSWORD VARCHAR2(500) NOT NULL,
	USERNAME VARCHAR2(500) NOT NULL,
	CONSTRAINT LOGIN_USERID_PK PRIMARY KEY (USERID)
);

INSERT INTO LOGIN
VALUES('hong', 'hong', '홍길동');