DROP SEQUENCE MODULBOARDSEQ;
DROP TABLE MODULBOARD;

CREATE SEQUENCE MODULBOARDSEQ;

CREATE TABLE MODULBOARD(
	SEQ NUMBER PRIMARY KEY,
	WRITER VARCHAR2(100) NOT NULL,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	REGDATE DATE NOT NULL
);

INSERT INTO MODULBOARD
VALUES (MODULBOARDSEQ.NEXTVAL, '테스트', '페이징을 위한', '페이징테스트입니다', SYSDATE);

SELECT SEQ, WRITER, TITLE, CONTENT, REGDATE
FROM MODULBOARD
ORDER BY SEQ DESC;


SELECT B.SEQ, B.WRITER, B.TITLE, B.CONTENT, B.REGDATE 
FROM 
	(SELECT ROWNUM AS RNUM, A.SEQ, A.WRITER, A.TITLE, A.CONTENT, A.REGDATE FROM 
	(SELECT SEQ, WRITER, TITLE, CONTENT, REGDATE FROM MODULBOARD
ORDER BY SEQ DESC) A
WHERE ROWNUM <= 23 ) B 
WHERE B.RNUM > 0;